pair_tag = ""
base_token = ""
base_token_address = ""
quote_token = ""
quote_token_address = ""
network_name = ""
chain_id = ""
gas_token_symbol = ""
gas_token_chainlink_price_feed = ""
explorer_url = ""
tycho_api = ""
target_spread_bps = ""
min_exec_spread_bps = ""
max_slippage_pct = ""
profitability_check = ""
max_inventory_ratio = ""
inclusion_block_delay = ""
tx_gas_limit = ""
block_offset = ""
permit2_address = ""
tycho_router_address = ""
poll_interval_ms = ""
publish_events = ""
min_publish_timeframe_ms = ""
[price_feed_config]
type = ""
source = ""
reverse = ""
