# === Global ===
pair_tag = "ðŸŸ£"
base_token = "ETH"
base_token_address = "0x4200000000000000000000000000000000000006"
quote_token = "USDC"
quote_token_address = "0x078D782b760474a361dDA0AF3839290b0EF57AD6"
network_name = "unichain"
chain_id = 130
wallet_public_key = "0xA61E420c6FB54F04c5D7a4818bA2DBAAC0120669"
gas_token_symbol = "0x4200000000000000000000000000000000000006"
gas_token_chainlink_price_feed = "0x5b0cf2b36a65a6BB085D501B971e4c102B9Cd473"
# rpc_url = "https://unichain-mainnet.blastapi.io/713ef8fa-d6fb-4192-bf47-3c924ec3ff6b"
# rpc_url = "https://0xrpc.io/uni"
rpc_url = "https://unichain.drpc.org"

explorer_url = "https://uniscan.xyz/"
tycho_api = "tycho-unichain-beta.propellerheads.xyz"

# === Execution ===
min_watch_spread_bps = 1.0
min_executable_spread_bps = -10.0 # <---- !
max_slippage_pct = 0.0025
max_inventory_ratio = 0.99 # <---- !
tx_gas_limit = 500000
block_offset = 1
inclusion_block_delay = 0
permit2_address = "0x000000000022d473030f116ddee9f6b43ac78ba3"
tycho_router_address = "0xFfA5ec2e444e4285108e4a17b82dA495c178427B"

# ! --- PROD --- !

# === Misc ===
poll_interval_ms = 2500
publish_events = false 
skip_simulation = false 
infinite_approval = false
min_publish_timeframe_ms = 60000

[price_feed_config]
type = "binance"
source = "https://api.binance.com/api/v3"
reverse = false
