# =========================================== Market Maker FuLL Configuration ===========================================

# === Global ===
pair_tag = "ðŸ”µ"
base_token = "ETH"
base_token_address = "0x4200000000000000000000000000000000000006"
quote_token = "USDC"
quote_token_address = "0x833589fcd6edb6e08f4c7c32d4f71b54bda02913"
network_name = "base"
chain_id = 8453
wallet_public_key = "0xF5029A50494714b3f80b39F05acC2c9Cea017FD6" # "0xC0F7d041defAE1045e11A6101284AbA4BCc3770f"
gas_token_symbol = "0x4200000000000000000000000000000000000006"
gas_token_chainlink_price_feed = "0x71041dddad3595F9CEd3DcCFBe3D1F4b0a16Bb70"
# rpc_url = "https://base-mainnet.blastapi.io/1437c115-f259-4690-a2d7-8c32e658a164"
rpc_url = "https://base-mainnet.g.alchemy.com/v2/lSi7J0gmr1jHBVV-gi29Z" # FlashBlock support ? Also support simulate, where the preconf doesn't support it ..
# rpc_url = "https://mainnet-preconf.base.org" # ! Can only be used if skip_simulation is true 
explorer_url = "https://basescan.org/"
tycho_api = "tycho-base-beta.propellerheads.xyz"

# === Execution ===
min_watch_spread_bps = 5.0
min_executable_spread_bps = 0.0
max_slippage_pct = 0.0005
max_inventory_ratio = 0.99

inclusion_block_delay = 0
tx_gas_limit = 300000
block_offset = 1
permit2_address = "0x000000000022D473030F116dDEE9F6B43aC78BA3"
tycho_router_address = "0xea3207778e39EB02D72C9D3c4Eac7E224ac5d369"

# === Misc ===
poll_interval_ms = 500
publish_events = true
skip_simulation = false # ! Very important parameter
infinite_approval = true
min_publish_timeframe_ms = 30000

[price_feed_config]
# type = "chainlink"
# source = "0x71041dddad3595F9CEd3DcCFBe3D1F4b0a16Bb70"
type = "binance"
source = "https://api.binance.com/api/v3"
reverse = false

