# =========================================== Market Maker FuLL Configuration ===========================================

# === Global ===
pair_tag = "⚪️"
base_token = "ETH"
base_token_address = "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
quote_token = "WBTC"
quote_token_address = "0x2260fac5e5542a773aa44fbcfedf7c193bc2c599"
network_name = "ethereum"
chain_id = 1
wallet_public_key = "0xF5029A50494714b3f80b39F05acC2c9Cea017FD6" # "0xC0F7d041defAE1045e11A6101284AbA4BCc3770f"
gas_token_symbol = "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
gas_token_chainlink_price_feed = "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
rpc_url = "https://eth-mainnet.blastapi.io/1437c115-f259-4690-a2d7-8c32e658a164"
explorer_url = "https://etherscan.io/"
tycho_api = "tycho-beta.propellerheads.xyz"

# === Execution ===
min_watch_spread_bps = 5.0
min_executable_spread_bps = 1.0
max_slippage_pct = 0.0005
max_inventory_ratio = 0.99

tx_gas_limit = 300000
block_offset = 1
inclusion_block_delay = 1
permit2_address = "0x000000000022D473030F116dDEE9F6B43aC78BA3"
tycho_router_address = "0xfD0b31d2E955fA55e3fa641Fe90e08b677188d35"

# === Misc ===
poll_interval_ms = 6000
publish_events = false 
skip_simulation = true # ! Very important parameter
infinite_approval = false
min_publish_timeframe_ms = 6000

[price_feed_config]
type = "chainlink"
source = "0xdeb288F737066589598e9214E782fa5A8eD689e8"
reverse = true

# BTC/ETH: 0xdeb288F737066589598e9214E782fa5A8eD689e8
# BTC/USD : 0xF4030086522a5bEEa4988F8cA5B36dbC97BeE88c