# === Global ===
pair_tag = "⚪️"
base_token = "ETH"
base_token_address = "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
quote_token = "USDC"
quote_token_address = "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
network_name = "ethereum"
chain_id = 1
wallet_public_key = "0x0aF694C17137ad1dE34e94335eA09608B715f20A"
gas_token_symbol = "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
gas_token_chainlink_price_feed = "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
rpc_url = "https://eth-mainnet.blastapi.io/1437c115-f259-4690-a2d7-8c32e658a164"
explorer_url = "https://etherscan.io/"
tycho_api = "tycho-beta.propellerheads.xyz"

# === Execution ===
min_watch_spread_bps = 5.0
min_executable_spread_bps = 5.0 # -10
max_slippage_pct = 0.0005
max_inventory_ratio = 0.99

tx_gas_limit = 300000
block_offset = 1
inclusion_block_delay = 1
permit2_address = "0x000000000022D473030F116dDEE9F6B43aC78BA3"
tycho_router_address = "0xfD0b31d2E955fA55e3fa641Fe90e08b677188d35"

# ! --- PROD --- !

# === Misc ===
poll_interval_ms = 6000
publish_events = true
skip_simulation = true
infinite_approval = true
min_publish_timeframe_ms = 30000

[price_feed_config]
# type = "chainlink"
# source = "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
# reverse = false
type = "binance"
source = "https://api.binance.com/api/v3"
reverse = false
