# =========================================== Market Maker FuLL Configuration ===========================================

# === Global ===
token0 = "ETH" # Base
addr0 = "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
token1 = "USDC" # Quote
addr1 = "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
network = "ethereum" # "base", "unichain"
rpc = "https://eth.llamarpc.com"
explorer = "https://etherscan.io/"
tycho_endpoint = "tycho-beta.propellerheads.xyz"
# === Execution ===
spread = 30 # Bps
slippage = 50
profitability = true
max_trade_allocation = 0.2
# bribe=0.5
broadcast = "buildernet"
gas_limit = 300000
target_block_offset = 1
permit2 = "0x000000000022D473030F116dDEE9F6B43aC78BA3"
tycho_router = "0x0178f471f219737c51d6005556d2f44de011a08a"
# === Misc ===
poll_interval_ms = 12000


[pfc] # ======= MM Price Feed Config ======= 
# Expected is token0 to token1 => if token0 is ETH and token1 USDC, then price is ~2500, not 0.0004
type = "binance"
source = "https://api.binance.com/api/v3"         
# type = "chainlink"                   
# source = "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
# type = "custom"
