# =========================================== Market Maker FuLL Configuration ===========================================

# === Global ===
token0 = "ETH" # Base
addr0 = "0x4200000000000000000000000000000000000006"
token1 = "USDC" # Quote
addr1 = "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
network = "unichain" # "base", "unichain"
gas_token = "0x4200000000000000000000000000000000000006" # Erc20
gas_token_chainlink = "0x0000000000000000000000000000000000000000" # Chainlink price feed for Gas Token (ETH) to USD
rpc = "https://unichain-mainnet.blastapi.io/1437c115-f259-4690-a2d7-8c32e658a164" # https://unichain.drpc.org"
explorer = "https://uniscan.xyz/"
tycho_endpoint = "tycho-unichain-beta.propellerheads.xyz"
# === Execution ===
spread = 30 # Bps
slippage = 50
profitability = true
max_trade_allocation = 0.2
# bribe=0.5
broadcast = "buildernet"
sampdepths = [500.0, 5000.0, 50000.0]

gas_limit = 300000
target_block_offset = 1
permit2 = "0x000000000022D473030F116dDEE9F6B43aC78BA3"
tycho_router = "0x9bdc3be75440dbe563527cb39bb11cfbd1e21b09"
# === Misc ===
poll_interval_ms = 1000

[pfc] # ======= MM Price Feed Config ======= 
# Expected price is token0 per token1 => if token0 is ETH and token1 USDC, then price is ~2500, not 0.0004
# type = "binance"
# source = "https://api.binance.com/api/v3"         
type = "chainlink"                   
source = "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
# type = "custom" 
# type = "twap" 