# =========================================== Market Maker FuLL Configuration ===========================================

# === Global ===
pair_tag = "ðŸŸ£"
base_token = "ETH"
base_token_address = "0x4200000000000000000000000000000000000006"
quote_token = "USDC"
quote_token_address = "0x078D782b760474a361dDA0AF3839290b0EF57AD6"
network_name = "unichain"
chain_id = 130
wallet_public_key = "0xF5029A50494714b3f80b39F05acC2c9Cea017FD6"
gas_token_symbol = "0x4200000000000000000000000000000000000006"
gas_token_chainlink_price_feed = ""
rpc_url = "https://unichain-mainnet.blastapi.io/713ef8fa-d6fb-4192-bf47-3c924ec3ff6b" # https://unichain.drpc.org
# rpc_url = "https://unichain-mainnet.blastapi.io/1437c115-f259-4690-a2d7-8c32e658a164" # https://unichain.drpc.org
explorer_url = "https://uniscan.xyz/"
tycho_api = "tycho-unichain-beta.propellerheads.xyz"

# === Execution ===
target_spread_bps = 5.0
min_exec_spread_bps = 0.0
max_slippage_pct = 0.0005
profitability_check = true
max_inventory_ratio = 0.5

tx_gas_limit = 300000
block_offset = 1
inclusion_block_delay = 0
permit2_address = "0x000000000022D473030F116dDEE9F6B43aC78BA3"
tycho_router_address = "0xFfA5ec2e444e4285108e4a17b82dA495c178427B"
skip_simulation = false # ! Very important parameter

#! fetch receipt boolean ?

# === Misc ===
poll_interval_ms = 250 # 250 ms for Unichain
publish_events = true 
min_publish_timeframe_ms = 12000

[price_feed_config]
type = "binance"
source = "https://api.binance.com/api/v3"
reverse = false

# type = "chainlink"                   
# source = "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
# reverse = false

